global using LibraryManagementSystem.ViewModel;
global using LibraryManagementSystem.ViewModel.BookViewModel;
global using LibraryManagementSystem.ViewModel.Members;
global using LibraryManagementSystem.ViewModel.Reservations;
global using LibraryManagementSystem.ViewModel.Penalties;
global using LibraryManagementSystem.ViewModel.BorrowsCopies;